title: "CuriousDose"
description: "Taking One Dose of Curiousity Everyday"
theme: minima

# GitHub Pages 설정
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Kim Jian"
  tagline: "Taking One Dose of Curiosity Everyday"
  location: "HAFS"
  email: "022094@hafs.hs.kr"
