title: "CuriousDose"
description: "최신 과학 트렌드를 가장 빠르게, Taking One Dose of Curiousity Everyday"
theme: minima

# GitHub Pages 설정
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Kim Jian"
  tagline: "Taking One Dose of Curiosity Everyday"
  location: "HAFS"
  email: "022094@hafs.hs.kr"
